//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public string profissao { get; set; }
        public string nacionalidade { get; set; }
        public int idade { get; set; }
        public string endereco { get; set; }
        public string rg { get; set; }
    }
}
